name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Build plugin
        run: |
          npm install --legacy-peer-deps

      - name: Run tests
        run: |
          npm run test
